### ISSUE TITLE
Patch for quick loot

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [Vermunds/SkyrimSoulsRE#3]
https://github.com/Vermunds/SkyrimSoulsRE/blob/197a8e159a76bd12be2bb0794dedcbeaf200a153/src/Events.cpp#L126-L133

This patch should no longer be necessary and is actually counter productive

**Comment by Vermunds** [comment]
I'm aware and it's already removed on my end. It was intended for the old version of the mod.
I changed a lot of things since this version, though it's not on Nexus yet as it's a going to be a major rework of the entire mod.
On that note, I should probably commit more often. Might as well start it now.
